[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"
authors = ["Tobias de Bruijn <t.debruijn@array21.dev>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.5.3"
ocl = "0.19.4"
lazy_static = "1.4.0"